routes/web.php
<?php

Route::namespace('Admin')->group(function(){
    Route::namespace('Auth')->group(function(){
        Route::get('/login', ['uses' => 'LoginController@showLoginForm', 'as' => 'login']);
        Route::post('/login', ['uses' => 'LoginController@login', 'as' => 'postLogin']);
        Route::post('/logout', ['uses' => 'LoginController@logout', 'as' => 'logout']);
    });
    
    Route::group(['middleware' => 'auth', 'prefix' => 'admin','as' => 'admin.'], function(){
        Route::get('/dashboard',['uses' => 'DashboardController@index', 'as' => 'dashboard']);
        Route::resource('/banners','BannerController');
        Route::resource('/services','ServiceController');
        Route::resource('/members','MemberController');
        Route::resource('/partners','PartnerController');
        Route::resource('/clients','ClientController');
        Route::resource('/blogs/categories','BlogCategoryController',['as' => 'blogs']);
        Route::resource('/blogs','BlogController');
        Route::resource('/portfolios/categories','PortfolioCategoryController',['as' => 'portfolios']);
        Route::resource('/portfolios','PortfolioController');
        Route::resource('/users/roles','RoleController',['as' => 'users']);
        Route::resource('/users','UserController');
        Route::resource('/settings','SettingController');

        // Save Image
        Route::post('/save-profile-image', ['as' => 'users.saveImage', 'uses' => 'UserController@saveImage']);
        Route::post('/save-banner-image', ['as' => 'banners.saveImage', 'uses' => 'BannerController@saveImage']);
        Route::post('/save-service-image', ['as' => 'services.saveImage', 'uses' => 'ServiceController@saveImage']);
        Route::post('/save-member-image', ['as' => 'members.saveImage', 'uses' => 'MemberController@saveImage']);
        Route::post('/save-partner-image', ['as' => 'partners.saveImage', 'uses' => 'PartnerController@saveImage']);
        Route::post('/save-client-image', ['as' => 'clients.saveImage', 'uses' => 'ClientController@saveImage']);
        Route::post('/save-portfolio-image', ['as' => 'portfolios.saveImage', 'uses' => 'PortfolioController@saveImage']);
        Route::post('/save-blog-image', ['as' => 'blogs.saveImage', 'uses' => 'BlogController@saveImage']);
        Route::post('/save-summernote-image',['as' => 'summernote.saveImage', 'uses' => 'ImageController@saveSummernoteImage']);
        Route::post('/save-image', ['as' => 'settings.saveImage', 'uses' => 'SettingController@saveImage']);
    });  
});

Route::namespace('Client')->group(function(){
    Route::get('/',['uses' => 'FrontendController@homepage','as' => 'client.homepage']);
});

app/Http/Controllers/Admin/ClientController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use DB;
use App\Model\Client;

class ClientController extends Controller
{
    public function index()
    {
        $clients = Client::orderBy('id','DESC')->paginate(10);
        
        return view('admin.client.index',compact('clients'));
    }

    public function create()
    {
        return view('admin.client.add-update');
    }

    public function store(Request $request)
    {
        $this->validate($request,[
            'image' => 'required'
        ]);
        $this->saveToDB($request->all());
        return redirect()->route('admin.clients.index')->withSuccess('You have just added a client successfully!');
    }

    public function edit($id)
    {
        $client = Client::findOrFail($id);
        return view('admin.client.add-update',compact('client'));
    }

    public function update(Request $request, $id)
    {  
        $this->saveToDB($request->all(),$id);
        return redirect()->route('admin.clients.index')->withSuccess('You have just updated a client successfully!');
    }

    public function destroy($id)
    {
       $result = false;
       $client = Client::find($id);
       if($client){
           DB::beginTransaction();
           try{
               if($client->delete()){
                   $result = true;
               }
               DB::commit();
           }catch(Exception $exception){
               DB::rollback();
               $result = false;
           }
       }
       return response()->json(['success' => $result]);
    }

    public function saveImage(Request $request){
       if($request->hasFile('file')){
           $path = saveTempImage($request->file('file'));
           return response()->json(['Status' => true, 'path' => $path]);
       }
       return response()->json(['Status' => false]);
   }

   public function deleteImage(){
       $result = false;
       $client_id = request()->get('client_id');
       DB::beginTransaction();
       try{
           $client = Client::findOrFail($client_id);
           if($client){
               $client->clearMediaCollection('images');
               $result = true;
           }
           DB::commit();
       }catch(Exception $exception){
           DB::rollback();
           $result = false;
       }
       
       return response()->json(['success' => $result]);
   }

    public function saveToDB($data, $id=null){
        DB::beginTransaction();
        try{
            $client = isset($id) ? Client::find($id) : new client;
            if(!$client) return redirect()->back()->withError('There is no record found!');

            $client->fill($data);
            if($client->save()){

               if(isset($data['image']) && !empty($data['image'])){
                   $client->clearMediaCollection('images'); 
                   $client->addMedia($data['image'])
                        ->toMediaCollection('images');
               }
            }

            DB::commit();
        }catch(Exception $ex){
            DB::rollback();
            return redirect()->back()->withError('There was an error during operation!');
        }
        return $client;
    }
}

app/Http/Controllers/Client/FrontendController.php
<?php

namespace App\Http\Controllers\Client;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\Banner;
use App\Model\Service;
use App\Model\Member;
use App\Model\Partner;
use App\Model\Client;
use App\Model\Portfolio;
use App\Model\PortfolioCategory;
use App\Model\Blog;

class FrontendController extends Controller
{
    public function homepage(){
        $constants = config()->get('constant.SETTING');
        $banners = Banner::whereState(1)->orderBy('id','DESC')->get();
        $services = Service::whereState(1)->orderBy('id','DESC')->get();
        $members = Member::whereState(1)->orderBy('id','ASC')->get();
        $partners = Partner::whereState(1)->orderBy('id','ASC')->get();
        $clients = Client::whereState(1)->orderBy('id','ASC')->get();
        $portfolios = Portfolio::whereState(1)->orderBy('id','DESC')->get();
        $portfolioCategories = PortfolioCategory::with('portfolios')->whereState(1)->get()->keyBy('id');
        $blogs = Blog::whereState(1)->orderBy('id','DESC')->get();
        return view('client.homepage.index',compact('constants','banners','services','members','partners','clients','portfolios','portfolioCategories','blogs'));
    }
}

resources/views/admin/client/add-update.blade.php
@extends('admin.layouts.master')

@section('custom-css')
<style>
    .dropzone .dz-preview .dz-image{
        width: 200px !important;
        height: 200px !important;
    }
</style>
@endsection

@section('content')
<!-- Page header -->
<div class="page-header page-header-light">
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex py-2">
            <h4><span class="font-weight-semibold">{{ isset($client) ? 'Edit' : 'Add'}} Client</span></h4>
        </div>

        <div class="header-elements d-none">
            <div class="d-flex justify-content-center">
                <a href="{{ route('admin.clients.create') }}" class="btn btn-primary mr-2">
                    <i class="icon-plus2 text-white"></i> Add New
                </a>
                <a href="{{route('admin.clients.index')}}" class="btn btn-primary">
                    <i class="icon-square-left mr-1"></i> Back
                </a>
            </div>
        </div>
    </div>

    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="{{route('admin.dashboard')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Dashboard</a>
                <a href="{{route('admin.clients.index')}}" class="breadcrumb-item">Client</a>
                <span class="breadcrumb-item active">{{ isset($client) ? 'Edit' : 'Add'}}</span>
            </div>
        </div>
    </div>
</div>
<!-- /page header -->

<div class="content">
    <div class="card">
        @if(isset($client))
        {{ Form::model($client,['route' => ['admin.clients.update',$client->id], 'method' => 'PUT']) }}
        @else
        {{ Form::open(['route' => 'admin.clients.store', 'method' => 'POST']) }}
        @endif
        @csrf
        <div class="card-body">
            <div class="row">
                <div class="col-lg-5">
                    <div class="form-group form-group-float form-group-feedback form-group-feedback-right">
                        <label class="form-group-float-label font-weight-semibold is-visible {{ $errors->has('image')?'text-danger':'' }}">client Image (Aspect Ratio 1:1)</label>
                        <div class="dropzone needsclick dz-clickable" action="{{ route('admin.clients.saveImage') }}" id="dropzoneClient">
                            @csrf
                        </div>
                        @if($errors->has('image'))
                            <span class="form-text text-danger">{{ $errors->first('image') }}</span>
                        @endif
                    </div>
                </div>
                <div class="col-lg-7">
                    <div class="form-group form-group-float form-group-feedback form-group-feedback-right">
                        <label class="form-group-float-label font-weight-semibold is-visible">Name</label>
                        <div class="position-relative">
                            {{Form::text("name",null,
                                ["class" => "form-control ","placeholder" => "Enter Name"])
                            }}
                        </div>
                    </div>

                    <div class="form-group form-group-float form-group-feedback form-group-feedback-right">
                        <label class="form-group-float-label font-weight-semibold is-visible">Link</label>
                        <div class="position-relative">
                            {{Form::text("link",null,
                                ["class" => "form-control ","placeholder" => "Enter Link"])
                            }}
                        </div>
                    </div>

                    <div class="form-group mb-3 mb-md-2">
                        <label class="d-block font-weight-semibold">State</label>
                        <div class="form-check custom-control-inline">
                            <label class="form-check-label">
                                <input type="radio" name="state" value="1" class="form-check-input-styled-success" data-fouc checked>
                                Enable
                            </label>
                        </div>
                        <div class="form-check custom-control-inline">
                            <label class="form-check-label">
                                <input type="radio" name="state" value="0" class="form-check-input-styled-danger" data-fouc 
                                    {{isset($client) && !$client->state ? 'checked' : '' }}>
                                    Disable
                            </label>
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-success">
                <i class="icon-folder mr-1"></i> Save
            </button>
        </div>

        @php $image = isset($client) ? $client->getMedia('images')->first() : null; @endphp
        @if(isset($client) && $image)
            <input type="hidden" name="image" id="image" value="{{old('image')}}" data-model-id="{{$client->id}}" data-name="{{$image->file_name}}" data-size="{{$image->size}}" data-url="{{ asset($image->getUrl()) }}">
        @else
            <input type="hidden" name="image" id="image" value="{{old('image')}}">
        @endif
        <input type="hidden" name="action" id="action" value="{{isset($client) ? 'update' : 'add'}}">
        {{ Form::close() }}
    </div>
</div>
@endsection

@section('page-script')
<script src="{{asset('admin/global_assets/js/plugins/forms/styling/uniform.min.js')}}"></script>}
<script src="{{asset('admin/global_assets/js/demo_pages/form_checkboxes_radios.js')}}"></script>
@endsection

resources/views/admin/client/index.blade.php
@extends('admin.layouts.master')

@section('content')
<!-- Page header -->
<div class="page-header page-header-light">
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex py-2">
            <h4><span class="font-weight-semibold">Client List</span></h4>
            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>

        <div class="header-elements d-none">
            @canany(['add-new-user'])
            <div class="d-flex justify-content-center">
                <a href="{{ route('admin.clients.create') }}" class="btn btn-link btn-primary btn-sm text-white">
                    <i class="icon-plus2 text-white"></i> Add New
                </a>
            </div>
            @endcanany
        </div>
    </div>

    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="{{route('admin.dashboard')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Dashboard</a>
                <span class="breadcrumb-item active">client</span>
                <span class="breadcrumb-item active">List</span>
            </div>

            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>
    </div>
</div>
<!-- /page header -->

<div class="content">
    <div class="card">
        @include('admin.includes.success-msg')
        @include('admin.includes.error-msg')
        <div class="table-responsive">
            <table class="table table-bordered">
                <thead>
                    <tr class="bg-slate-800">
                        <th>#</th>
                        <th>Logo</th>
                        <th>Name</th>
                        <th>State</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @if(isset($clients) && $clients->count() > 0)
                        @foreach($clients as $key => $row)
                        @php $image = $row->getFirstMedia('images'); @endphp
                        <tr>
                            <td>{{($clients->perPage() * ($clients->currentPage() - 1)) + $key + 1}}</td>
                            <td>
                                @if($image)
                                    <img width="70px" src="{{asset($image->getUrl())}}" alt="{{ $row->name }}">
                                @endif
                            </td>
                            <td>{!! $row->name !!} <a href="{{$row->link ?: '#'}}" target="_BLANK"><i class="icon-hyperlink"></i></a></td>
                            <td>
                                @if($row->state)
                                    <span class="badge badge-success">Active</span>
                                @else
                                    <span class="badge badge-danger">Deactive</span>
                                @endif
                            </td>
                            <td class="group-btn-action">
                                @canany(['user-modification'])
                                    <a href="{{ route('admin.clients.edit',$row->id) }}" class="btn btn-sm btn-outline bg-primary border-primary text-primary-800 btn-icon border-2" data-popup="tooltip" title="" data-placement="bottom" data-original-title="Edit"><i class="icon-pencil7"></i></a>
                                    <button class="btn btn-sm btn-outline bg-danger border-danger text-danger-800 btn-icon border-2 delete" data-route="{{route('admin.clients.destroy',$row->id)}}" data-popup="tooltip" title="" data-placement="bottom" data-original-title="Delete"><i class="icon-trash"></i></button>
                                @endcanany
                            </td>
                        </tr>
                        @endforeach
                    @else
                        <tr><td colspan="5">No Data</td></tr>
                    @endif
                </tbody>
            </table>
        </div>
        @if(isset($clients) && $clients->count() > 0)
        <div class="card-footer">
            @if($clients->hasMorePages())
                <div class="mb-2">
                    {!! $clients->appends(Request::except('page'))->render() !!}
                </div>
            @endif
            <div>
                Showing {{$clients->firstItem()}} to {{$clients->lastItem()}}
                of  {{$clients->total()}} entries
            </div>
        </div>
        @endif
    </div>
</div>
@endsection