routes/web.php
<?php

Route::namespace('Admin')->group(function(){
    Route::namespace('Auth')->group(function(){
        Route::get('/login', ['uses' => 'LoginController@showLoginForm', 'as' => 'login']);
        Route::post('/login', ['uses' => 'LoginController@login', 'as' => 'postLogin']);
        Route::post('/logout', ['uses' => 'LoginController@logout', 'as' => 'logout']);
    });
    
    Route::group(['middleware' => 'auth', 'prefix' => 'admin','as' => 'admin.'], function(){
        Route::get('/dashboard',['uses' => 'DashboardController@index', 'as' => 'dashboard']);
        Route::resource('/banners','BannerController');
        Route::resource('/services','ServiceController');
        Route::resource('/members','MemberController');
        Route::resource('/partners','PartnerController');
        Route::resource('/clients','ClientController');
        Route::resource('/blogs/categories','BlogCategoryController',['as' => 'blogs']);
        Route::resource('/blogs','BlogController');
        Route::resource('/portfolios/categories','PortfolioCategoryController',['as' => 'portfolios']);
        Route::resource('/portfolios','PortfolioController');
        Route::resource('/users/roles','RoleController',['as' => 'users']);
        Route::resource('/users','UserController');
        Route::resource('/settings','SettingController');

        // Save Image
        Route::post('/save-profile-image', ['as' => 'users.saveImage', 'uses' => 'UserController@saveImage']);
        Route::post('/save-banner-image', ['as' => 'banners.saveImage', 'uses' => 'BannerController@saveImage']);
        Route::post('/save-service-image', ['as' => 'services.saveImage', 'uses' => 'ServiceController@saveImage']);
        Route::post('/save-member-image', ['as' => 'members.saveImage', 'uses' => 'MemberController@saveImage']);
        Route::post('/save-partner-image', ['as' => 'partners.saveImage', 'uses' => 'PartnerController@saveImage']);
        Route::post('/save-client-image', ['as' => 'clients.saveImage', 'uses' => 'ClientController@saveImage']);
        Route::post('/save-portfolio-image', ['as' => 'portfolios.saveImage', 'uses' => 'PortfolioController@saveImage']);
        Route::post('/save-blog-image', ['as' => 'blogs.saveImage', 'uses' => 'BlogController@saveImage']);
        Route::post('/save-summernote-image',['as' => 'summernote.saveImage', 'uses' => 'ImageController@saveSummernoteImage']);
        Route::post('/save-image', ['as' => 'settings.saveImage', 'uses' => 'SettingController@saveImage']);
    });  
});

Route::namespace('Client')->group(function(){
    Route::get('/',['uses' => 'FrontendController@homepage','as' => 'client.homepage']);
});

app/Http/Controllers/Admin/PortfolioController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use DB;
use App\Model\Portfolio;
use App\Model\PortfolioCategory;

class PortfolioController extends Controller
{
    public function index()
    {
        $portfolios = Portfolio::orderBy('id','DESC')->paginate(10);

        return view('admin.portfolio.list.index',compact('portfolios'));
    }

    public function create()
    {
        $categories = PortfolioCategory::orderBy('name','ASC')->pluck('name','id')->toArray();
        $categories = ['0' => 'Choose a category'] + $categories;

        return view('admin.portfolio.list.add-update', compact('categories'));
    }

    public function store(Request $request)
    {
        $this->validate($request,[
            'image' => 'required',
            'name' => 'required',
        ]);
        $this->saveToDB($request->all());
        return redirect()->route('admin.portfolios.index')->withSuccess('You have just added a portfolio successfully!');
    }

    public function edit($id)
    {
        $portfolio = Portfolio::findOrFail($id);
        $categories = PortfolioCategory::orderBy('name','ASC')->pluck('name','id')->toArray();
        $categories = ['0' => 'Choose a category'] + $categories;
        return view('admin.portfolio.list.add-update',compact('portfolio','categories'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'name' => 'required'
        ]);
        $this->saveToDB($request->all(),$id);
        return redirect()->route('admin.portfolios.index')->withSuccess('You have just updated a portfolio successfully!');
    }

    public function destroy($id)
    {
       $result = false;
       $portfolio = Portfolio::find($id);
       if($portfolio){
           DB::beginTransaction();
           try{
               if($portfolio->delete()){
                   $result = true;
               }
               DB::commit();
           }catch(Exception $exception){
               DB::rollback();
               $result = false;
           }
       }
       return response()->json(['success' => $result]);
    }

    public function saveImage(Request $request){
       if($request->hasFile('file')){
           $path = saveTempImage($request->file('file'));
           return response()->json(['Status' => true, 'path' => $path]);
       }
       return response()->json(['Status' => false]);
   }

    public function deleteImage(){
        $result = false;
        $portfolio_id = request()->get('portfolio_id');
        DB::beginTransaction();
        try{
            $portfolio = Portfolio::findOrFail($portfolio_id);
            if($portfolio){
                $portfolio->clearMediaCollection('images');
                $result = true;
            }
            DB::commit();
        }catch(Exception $exception){
            DB::rollback();
            $result = false;
        }

        return response()->json(['success' => $result]);
    }

    public function saveToDB($data, $id=null){
        DB::beginTransaction();
        try{
            $portfolio = isset($id) ? Portfolio::find($id) : new portfolio;
            if(!$portfolio) return redirect()->back()->withError('There is no record found!');

            $portfolio->fill($data);
            if($portfolio->save()){

               if(isset($data['image']) && !empty($data['image'])){
                   $filename = generateFileName($portfolio->name);
                   $portfolio->clearMediaCollection('images');
                   $portfolio->addMedia($data['image'])
                        ->usingName($filename)
                        ->usingFileName($filename.'.'.pathinfo($data['image'], PATHINFO_EXTENSION))
                        ->toMediaCollection('images');
               }
            }

            DB::commit();
        }catch(Exception $ex){
            DB::rollback();
            return redirect()->back()->withError('There was an error during operation!');
        }
        return $portfolio;
    }
}

resources/views/admin/portfolio/list/add-update.blade.php
@extends('admin.layouts.master')

@section('custom-css')
<style>
    .dropzone .dz-preview .dz-image{
        width: 200px !important;
        height: 200px !important;
    }
</style>
@endsection

@section('content')
<!-- Page header -->
<div class="page-header page-header-light">
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex py-2">
            <h4><span class="font-weight-semibold">{{ isset($portfolio) ? 'Edit' : 'Add'}} portfolio</span></h4>
        </div>

        <div class="header-elements d-none">
            <div class="d-flex justify-content-center">
                <a href="{{ route('admin.portfolios.create') }}" class="btn btn-primary mr-2">
                    <i class="icon-plus2 text-white"></i> Add New
                </a>
                <a href="{{route('admin.portfolios.index')}}" class="btn btn-primary">
                    <i class="icon-square-left mr-1"></i> Back
                </a>
            </div>
        </div>
    </div>

    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="{{route('admin.dashboard')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Dashboard</a>
                <a href="{{route('admin.portfolios.index')}}" class="breadcrumb-item">Portfolio</a>
                <span class="breadcrumb-item active">{{ isset($portfolio) ? 'Edit' : 'Add'}}</span>
            </div>
        </div>
    </div>
</div>
<!-- /page header -->

<div class="content">
    <div class="card">
        @if(isset($portfolio))
        {{ Form::model($portfolio,['route' => ['admin.portfolios.update',$portfolio->id], 'method' => 'PUT']) }}
        @else
        {{ Form::open(['route' => 'admin.portfolios.store', 'method' => 'POST']) }}
        @endif
        @csrf
        <div class="card-body">
            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group form-group-float form-group-feedback form-group-feedback-right">
                        <label class="form-group-float-label font-weight-semibold is-visible {{ $errors->has('name')?'text-danger':'' }}">Name</label>
                        <div class="position-relative">
                            {{Form::text("name",null,
                                ["class" => "form-control ".($errors->has('name')?'border-danger':''),"placeholder" => "Enter username"])
                            }}
                            @if($errors->has('name'))
                                <div class="form-control-feedback text-danger">
                                    <i class="icon-spam"></i>
                                </div>
                            @endif
                        </div>
                        @if($errors->has('name'))
                            <span class="form-text text-danger">{{ $errors->first('name') }}</span>
                        @endif
                    </div>

                    <div class="form-group form-group-float form-group-feedback form-group-feedback-right">
                        <label class="form-group-float-label font-weight-semibold is-visible {{ $errors->has('link')?'text-danger':'' }}">Url Link</label>
                        <div class="position-relative">
                            {{Form::text("link",null,
                                ["class" => "form-control ".($errors->has('link')?'border-danger':''),"placeholder" => "Enter url link"])
                            }}
                            @if($errors->has('link'))
                                <div class="form-control-feedback text-danger">
                                    <i class="icon-spam"></i>
                                </div>
                            @endif
                        </div>
                        @if($errors->has('link'))
                            <span class="form-text text-danger">{{ $errors->first('link') }}</span>
                        @endif
                    </div>

                    <div class="form-group form-group-float form-group-feedback form-group-feedback-right">
                        <label class="form-group-float-label font-weight-semibold is-visible {{ $errors->has('description')?'text-danger':'' }}">Description</label>
                        <div class="position-relative">
                            {{Form::textarea("description",null,
                                ["class" => "form-control ".($errors->has('description')?'border-danger':''),"placeholder" => "Enter description",'rows' => 5])
                            }}
                            @if($errors->has('description'))
                                <div class="form-control-feedback text-danger">
                                    <i class="icon-spam"></i>
                                </div>
                            @endif
                        </div>
                        @if($errors->has('description'))
                            <span class="form-text text-danger">{{ $errors->first('description') }}</span>
                        @endif
                    </div>

                    <div class="form-group select2">
                        <label>Categories</label>
                        {{Form::select("portfolio_category_id",$categories, isset($portfolio,$portfolio->category) ? $portfolio->category->id : null,["class" => "form-control"])}}
                    </div>

                    <div class="form-group mb-3 mb-md-2">
                        <label class="d-block font-weight-semibold">State</label>
                        <div class="form-check custom-control-inline">
                            <label class="form-check-label">
                                <input type="radio" name="state" value="1" class="form-check-input-styled-success" data-fouc checked>
                                Enable
                            </label>
                        </div>
                        <div class="form-check custom-control-inline">
                            <label class="form-check-label">
                                <input type="radio" name="state" value="0" class="form-check-input-styled-danger" data-fouc
                                    {{isset($user) && !$user->state ? 'checked' : '' }}>
                                    Disable
                            </label>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group form-group-float form-group-feedback form-group-feedback-right">
                        <label class="form-group-float-label font-weight-semibold is-visible {{ $errors->has('image')?'text-danger':'' }}">Image (Aspect Ratio 1:1)</label>
                        <div class="dropzone needsclick dz-clickable" action="{{ route('admin.portfolios.saveImage') }}" id="dropzonePortfolio">
                            @csrf
                        </div>
                        @if($errors->has('image'))
                            <span class="form-text text-danger">{{ $errors->first('image') }}</span>
                        @endif
                    </div>
                </div>

            </div>

        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-success">
                <i class="icon-folder mr-1"></i> Save
            </button>
        </div>

        @php $image = isset($portfolio) ? $portfolio->getMedia('images')->first() : null; @endphp
        @if(isset($portfolio) && $image)
            <input type="hidden" name="image" id="image" value="{{old('image')}}" data-model-id="{{$portfolio->id}}" data-name="{{$image->file_name}}" data-size="{{$image->size}}" data-url="{{ asset($image->getUrl('thumb')) }}">
        @else
            <input type="hidden" name="image" id="image" value="{{old('image')}}">
        @endif
        <input type="hidden" name="action" id="action" value="{{isset($portfolio) ? 'update' : 'add'}}">
        {{ Form::close() }}
    </div>
</div>
@endsection

@section('page-script')
<script src="{{asset('admin/global_assets/js/plugins/forms/styling/uniform.min.js')}}"></script>}
<script src="{{asset('admin/global_assets/js/demo_pages/form_checkboxes_radios.js')}}"></script>
@endsection

resources/views/admin/portfolio/list/index.blade.php
@extends('admin.layouts.master')

@section('content')
<!-- Page header -->
<div class="page-header page-header-light">
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex py-2">
            <h4><span class="font-weight-semibold">Portfolio List</span></h4>
            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>

        <div class="header-elements d-none">
            @canany(['add-new-user'])
            <div class="d-flex justify-content-center">
                <a href="{{ route('admin.portfolios.create') }}" class="btn btn-link btn-primary btn-sm text-white">
                    <i class="icon-plus2 text-white"></i> Add New
                </a>
            </div>
            @endcanany
        </div>
    </div>

    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="{{route('admin.dashboard')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Dashboard</a>
                <span class="breadcrumb-item active">Portfolio</span>
                <span class="breadcrumb-item active">List</span>
            </div>

            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>
    </div>
</div>
<!-- /page header -->

<div class="content">
    <div class="card">
        @include('admin.includes.success-msg')
        @include('admin.includes.error-msg')
        <div class="table-responsive">
            <table class="table table-bordered">
                <thead>
                    <tr class="bg-slate-800">
                        <th>#</th>
                        <th>Image</th>
                        <th>Name</th>
                        <th>Category</th>
                        <th>State</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @if(isset($portfolios) && $portfolios->count() > 0)
                        @foreach($portfolios as $key => $row)
                        @php $image = $row->getFirstMediaUrl('images', 'thumb'); @endphp
                        <tr>
                            <td>{{($portfolios->perPage() * ($portfolios->currentPage() - 1)) + $key + 1}}</td>
                            <td>
                                @if($image)
                                    <img width="100px" src="{{asset($image)}}" alt="{{ $row->name }}">
                                @endif
                            </td>
                            <td>{!! $row->name !!} <a href="{{ $row->link ?: '#'}}" target="_BLANK"><i class="icon-hyperlink"></i></a></td>
                            <td>{!! $row->category ? $row->category->name : '' !!}</td>
                            <td>
                                @if($row->state)
                                    <span class="badge badge-success">Active</span>
                                @else
                                    <span class="badge badge-danger">Deactive</span>
                                @endif
                            </td>
                            <td class="group-btn-action">
                                @canany(['user-modification'])
                                    <a href="{{ route('admin.portfolios.edit',$row->id) }}" class="btn btn-sm btn-outline bg-primary border-primary text-primary-800 btn-icon border-2" data-popup="tooltip" title="" data-placement="bottom" data-original-title="Edit"><i class="icon-pencil7"></i></a>
                                    <button class="btn btn-sm btn-outline bg-danger border-danger text-danger-800 btn-icon border-2 delete" data-route="{{route('admin.portfolios.destroy',$row->id)}}" data-popup="tooltip" title="" data-placement="bottom" data-original-title="Delete"><i class="icon-trash"></i></button>
                                @endcanany
                            </td>
                        </tr>
                        @endforeach
                    @else
                        <tr><td colspan="6">No Data</td></tr>
                    @endif
                </tbody>
            </table>
        </div>
        @if(isset($portfolios) && $portfolios->count() > 0)
        <div class="card-footer">
            @if($portfolios->hasMorePages())
                <div class="mb-2">
                    {!! $portfolios->appends(Request::except('page'))->render() !!}
                </div>
            @endif
            <div>
                Showing {{$portfolios->firstItem()}} to {{$portfolios->lastItem()}}
                of  {{$portfolios->total()}} entries
            </div>
        </div>
        @endif
    </div>
</div>
@endsection