routes/web.php
<?php

Route::namespace('Admin')->group(function(){
    Route::namespace('Auth')->group(function(){
        Route::get('/login', ['uses' => 'LoginController@showLoginForm', 'as' => 'login']);
        Route::post('/login', ['uses' => 'LoginController@login', 'as' => 'postLogin']);
        Route::post('/logout', ['uses' => 'LoginController@logout', 'as' => 'logout']);
    });
    
    Route::group(['middleware' => 'auth', 'prefix' => 'admin','as' => 'admin.'], function(){
        Route::get('/dashboard',['uses' => 'DashboardController@index', 'as' => 'dashboard']);
        Route::resource('/banners','BannerController');
        Route::resource('/services','ServiceController');
        Route::resource('/members','MemberController');
        Route::resource('/partners','PartnerController');
        Route::resource('/clients','ClientController');
        Route::resource('/blogs/categories','BlogCategoryController',['as' => 'blogs']);
        Route::resource('/blogs','BlogController');
        Route::resource('/portfolios/categories','PortfolioCategoryController',['as' => 'portfolios']);
        Route::resource('/portfolios','PortfolioController');
        Route::resource('/users/roles','RoleController',['as' => 'users']);
        Route::resource('/users','UserController');
        Route::resource('/settings','SettingController');

        // Save Image
        Route::post('/save-profile-image', ['as' => 'users.saveImage', 'uses' => 'UserController@saveImage']);
        Route::post('/save-banner-image', ['as' => 'banners.saveImage', 'uses' => 'BannerController@saveImage']);
        Route::post('/save-service-image', ['as' => 'services.saveImage', 'uses' => 'ServiceController@saveImage']);
        Route::post('/save-member-image', ['as' => 'members.saveImage', 'uses' => 'MemberController@saveImage']);
        Route::post('/save-partner-image', ['as' => 'partners.saveImage', 'uses' => 'PartnerController@saveImage']);
        Route::post('/save-client-image', ['as' => 'clients.saveImage', 'uses' => 'ClientController@saveImage']);
        Route::post('/save-portfolio-image', ['as' => 'portfolios.saveImage', 'uses' => 'PortfolioController@saveImage']);
        Route::post('/save-blog-image', ['as' => 'blogs.saveImage', 'uses' => 'BlogController@saveImage']);
        Route::post('/save-summernote-image',['as' => 'summernote.saveImage', 'uses' => 'ImageController@saveSummernoteImage']);
        Route::post('/save-image', ['as' => 'settings.saveImage', 'uses' => 'SettingController@saveImage']);
    });  
});

Route::namespace('Client')->group(function(){
    Route::get('/',['uses' => 'FrontendController@homepage','as' => 'client.homepage']);
});

resources/views/admin/layouts/head.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="csrf-token" content="{{ csrf_token() }}" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Mkoratec - Infinite Solution</title>
<link rel="icon" type="image/png" href="{{ asset('client/images/favicon.png') }}">
<link rel="apple-touch-icon" href="{{ asset('client/images/favicon.png') }}">

<!-- Global stylesheets -->
<link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
<link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.11/summernote.css" rel="stylesheet">
{{-- <link href="/admin/global_assets/css/icons/icomoon/styles.min.css" rel="stylesheet" type="text/css">
<link href="/admin/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css">
<link href="/admin/assets/css/bootstrap_limitless.min.css" rel="stylesheet" type="text/css">
<link href="/admin/assets/css/layout.min.css" rel="stylesheet" type="text/css">
<link href="/admin/assets/css/components.min.css" rel="stylesheet" type="text/css">
<link href="/admin/assets/css/colors.min.css" rel="stylesheet" type="text/css"> --}}
<!-- /global stylesheets -->
<link href="{{ asset('admin/assets/css/all.min.css')}}" rel="stylesheet" type="text/css">
<link href="/admin//assets/css/custom.css" rel="stylesheet" type="text/css">

@yield('custom-css')

resources/views/admin/layouts/header.blade.php
<div class="navbar navbar-expand-md navbar-dark">
    <div class="navbar-brand">
        <a href="index.html" class="d-inline-block">
            <img src="{{asset('admin/assets/images/text-logo.png')}}" alt="">
        </a>
    </div>

    <div class="d-md-none">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-mobile">
            <i class="icon-tree5"></i>
        </button>
        <button class="navbar-toggler sidebar-mobile-main-toggle" type="button">
            <i class="icon-paragraph-justify3"></i>
        </button>
    </div>

    <div class="collapse navbar-collapse" id="navbar-mobile">
        <span class="badge bg-success ml-md-3 mr-md-auto">Online</span>

        <ul class="navbar-nav">
            <li class="nav-item dropdown dropdown-user">
                @php $auth = auth()->user(); $image = $auth->getFirstMedia('images'); @endphp
                <a href="#" class="navbar-nav-link d-flex align-items-center dropdown-toggle" data-toggle="dropdown">
                    <img src="{{ $image ? $image->getUrl() : ''}}" class="rounded-circle mr-2" height="34" alt="">
                    <span>{{ $auth ? $auth->name : env('APP_NAME') }}</span>
                </a>

                <div class="dropdown-menu dropdown-menu-right">
                    <a href="{{route('admin.users.edit',auth()->id())}}" class="dropdown-item"><i class="icon-key"></i> Edit Password</a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item" onclick="event.preventDefault(); document.getElementById('frm-logout').submit();"><i class="icon-switch2"></i> Logout</a>
                    <form id="frm-logout" action="{{route('logout')}}" method="POST" style="display: none;">
                        {{ csrf_field() }}
                    </form>
                </div>
            </li>
        </ul>
    </div>
</div>

resources/views/admin/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">
<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<head>
	@include('admin.layouts.head')
</head>
<body>
	@include('admin.layouts.header')  
	
	<!-- Page content -->
	<div class="page-content">
		<!-- Main sidebar -->
		<div class="sidebar sidebar-dark sidebar-main sidebar-expand-md">

			<!-- Sidebar mobile toggler -->
			<div class="sidebar-mobile-toggler text-center">
				<a href="#" class="sidebar-mobile-main-toggle">
					<i class="icon-arrow-left8"></i>
				</a>
				Navigation
				<a href="#" class="sidebar-mobile-expand">
					<i class="icon-screen-full"></i>
					<i class="icon-screen-normal"></i>
				</a>
			</div>
			<!-- /sidebar mobile toggler -->


			<!-- Sidebar content -->
			<div class="sidebar-content">

				<!-- User menu -->
				<div class="sidebar-user">
					<div class="card-body">
						<div class="media">
							@php $auth = auth()->user(); $image = $auth->getFirstMedia('images');@endphp
							<div class="mr-3">
								<a href="#"><img src="{{ $image ? $image->getUrl() : ''}}" width="38" height="38" class="rounded-circle" alt=""></a>
							</div>

							<div class="media-body">
								<div class="media-title font-weight-semibold">{{ $auth ? $auth->name : env('APP_NAME') }}</div>
								<div class="font-size-xs opacity-50">
									{{ $auth &&  $auth->roles && count($auth->roles) > 0 ? $auth->roles[0]->name : '' }}
								</div>
							</div>
						</div>
					</div>
				</div>
				<!-- /user menu -->


				<!-- Main navigation -->
				<div class="card card-sidebar-mobile">
					<ul class="nav nav-sidebar" data-nav-type="accordion">
						@include('admin.layouts.sidebar')
					</ul>
				</div>
				<!-- /main navigation -->

			</div>
			<!-- /sidebar content -->
			
		</div>
		<!-- /main sidebar -->

		<!-- Main content -->
		<div class="content-wrapper">
			@yield('content')
			<!-- Footer -->
			<div class="navbar navbar-expand-lg navbar-light">
				<div class="text-center d-lg-none w-100">
					<button type="button" class="navbar-toggler dropdown-toggle" data-toggle="collapse" data-target="#navbar-footer">
						<i class="icon-unfold mr-2"></i>
						Footer
					</button>
				</div>

				<div class="navbar-collapse collapse" id="navbar-footer">
					<span class="navbar-text">
						&copy; {{ date('Y') }}. <a href="{{ isset($settings['company']['site_url']) ? $settings['company']['site_url']->value : '#' }}">Mkoratec - Infinite Solution</a>
					</span>

				</div>
			</div>
			<!-- /footer -->
		</div>
		<!-- /main content -->
	</div>
	<!-- /page content -->
	<input type="hidden" name="constant" id="constant" value="{{ json_encode(config()->get('constant.SETTING')) }}">
	<input type="hidden" name="baseUrl" id="baseUrl" value="{{ url('/') }}">
	@include('admin.layouts.script')
</body>

</html>

resources/views/admin/layouts/script.blade.php
<script src="{{asset('admin/assets/js/app.js')}}"></script>
<script src="{{asset('admin/global_assets/js/main/jquery.min.js')}}"></script>
<script src="{{asset('admin/global_assets/js/main/bootstrap.bundle.min.js')}}"></script>
<script src="{{asset('admin/global_assets/js/plugins/loaders/blockui.min.js')}}"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.11/summernote.js"></script>
<script src="/admin/global_assets/js/plugins/uploaders/dropzone.min.js"></script>
<script src="/admin/global_assets/js/demo_pages/uploader_dropzone.js"></script>
@yield('page-script')
<script src="{{asset('admin/assets/js/custom.js')}}"></script>
<script src="{{asset('admin/assets/js/dropzone.js')}}"></script>
<script src="{{asset('admin/assets/js/summernote.js')}}"></script>

@yield('custom-js')

resources/views/admin/layouts/sidebar.blade.php
<li class="nav-item-header"><div class="text-uppercase font-size-xs line-height-xs">Main</div> <i class="icon-menu" title="Main"></i></li>

<li class="nav-item">
    <a href="{{ route('admin.dashboard') }}" class="nav-link"><i class="icon-home4"></i> <span>Dashboard</span></a>
</li>

<li class="nav-item">
    <a href="{{ route('admin.settings.index') }}" class="nav-link"><i class="icon-home4"></i> <span>Company Setting</span></a>
</li>

<li class="nav-item">
    <a href="{{ route('admin.banners.index') }}" class="nav-link"><i class="icon-home4"></i> <span>Banner</span></a>
</li>

<li class="nav-item nav-item-submenu">
    <a href="#" class="nav-link"><i class="icon-coins"></i> <span>Portfolio</span></a>
    <ul class="nav nav-group-sub" data-submenu-title="Layouts">
        <li class="nav-item">
            <a href="{{ route('admin.portfolios.index') }}" class="nav-link">List</a>
        </li>
        <li class="nav-item">
            <a href="{{ route('admin.portfolios.categories.index') }}" class="nav-link">Category</a>
        </li>
    </ul>
</li>

<li class="nav-item">
    <a href="{{ route('admin.services.index') }}" class="nav-link"><i class="icon-home4"></i> <span>Service</span></a>
</li>

<li class="nav-item">
    <a href="{{ route('admin.members.index') }}" class="nav-link"><i class="icon-home4"></i> <span>Team Member</span></a>
</li>

<li class="nav-item nav-item-submenu">
    <a href="#" class="nav-link"><i class="icon-coins"></i> <span>Blog</span></a>
    <ul class="nav nav-group-sub" data-submenu-title="Layouts">
        <li class="nav-item">
            <a href="{{ route('admin.blogs.index') }}" class="nav-link">List</a>
        </li>
        <li class="nav-item">
            <a href="{{ route('admin.blogs.categories.index') }}" class="nav-link">Category</a>
        </li>
    </ul>
</li>

<li class="nav-item">
    <a href="{{ route('admin.partners.index') }}" class="nav-link"><i class="icon-home4"></i> <span>Partner</span></a>
</li>

<li class="nav-item">
    <a href="{{ route('admin.clients.index') }}" class="nav-link"><i class="icon-home4"></i> <span>Client</span></a>
</li>

<li class="nav-item nav-item-submenu">
    <a href="#" class="nav-link"><i class="icon-coins"></i> <span>User</span></a>
    <ul class="nav nav-group-sub" data-submenu-title="Layouts">
        <li class="nav-item">
            <a href="{{route('admin.users.index')}}" class="nav-link">User List</a>
        </li>
        <li class="nav-item">
            <a href="{{route('admin.users.roles.index')}}" class="nav-link">Role List</a>
        </li>
    </ul>
</li>